# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Daniel Benedí García
        author_email: 774156@unizar.es
        message: 'Auto-build'
        add: 'build'
    - name: Archive build results
      uses: actions/upload-artifact@v2
      with:
        path: build
    - name: Copy build
      run: |
        git config --global user.email "774156@unizar.es"
        git config --global user.name "Daniel Benedí García"
        cd ..
        git clone --branch Deployment https://github.com/UNIZAR-30226-2021-13/UniTrivia_backend.git
        cd UniTrivia_backend
        cp -r ../UniTrivia_frontend/build .
        git add build
        git commit -m "Auto-build webpage" --author "Daniel Benedí García <774156@unizar.es>"
        git push remotes/origin/Deployment
